name: Test React App
on: push
jobs:
    runs-on: ubuntu-latest
    steps:
        - name: Get repository vode
          uses: actions/checkout#v3
        - name: Instal dependencies
          run: npm ci
        - name: Test app
          run: nmp run test
